Search.appendIndex(
    [
                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge",
            "name": "Edge",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Edge.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020Edge\u0020instance",
            "url": "classes/Locospec-EnginePhp-Edge.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "Returns\u0020the\u0020source\u0020vertex",
            "url": "classes/Locospec-EnginePhp-Edge.html#method_getSource"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003AgetTarget\u0028\u0029",
            "name": "getTarget",
            "summary": "Returns\u0020the\u0020target\u0020vertex",
            "url": "classes/Locospec-EnginePhp-Edge.html#method_getTarget"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Returns\u0020the\u0020edge\u0020type",
            "url": "classes/Locospec-EnginePhp-Edge.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Returns\u0020the\u0020edge\u0020data",
            "url": "classes/Locospec-EnginePhp-Edge.html#method_getData"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "Sets\u0020new\u0020data\u0020for\u0020the\u0020edge",
            "url": "classes/Locospec-EnginePhp-Edge.html#method_setData"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003A\u0024source",
            "name": "source",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Edge.html#property_source"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003A\u0024target",
            "name": "target",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Edge.html#property_target"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Edge.html#property_type"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Edge\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Edge.html#property_data"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass",
            "name": "EnginePhpClass",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass\u003A\u003AprocessSpecificationFile\u0028\u0029",
            "name": "processSpecificationFile",
            "summary": "Process\u0020specifications\u0020from\u0020a\u0020JSON\u0020file\u0020path",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html#method_processSpecificationFile"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass\u003A\u003AprocessSpecificationJson\u0028\u0029",
            "name": "processSpecificationJson",
            "summary": "Process\u0020specifications\u0020directly\u0020from\u0020a\u0020JSON\u0020string",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html#method_processSpecificationJson"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass\u003A\u003AgetRegistryManager\u0028\u0029",
            "name": "getRegistryManager",
            "summary": "Get\u0020the\u0020registry\u0020manager\u0020instance",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html#method_getRegistryManager"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass\u003A\u003A\u0024registryManager",
            "name": "registryManager",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html#property_registryManager"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\EnginePhpClass\u003A\u003A\u0024specProcessor",
            "name": "specProcessor",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-EnginePhpClass.html#property_specProcessor"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Exceptions\\DuplicateVertexException",
            "name": "DuplicateVertexException",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Exceptions-DuplicateVertexException.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Exceptions\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Exceptions-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Exceptions\\VertexNotFoundException",
            "name": "VertexNotFoundException",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Exceptions-VertexNotFoundException.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph",
            "name": "Graph",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020Graph\u0020instance",
            "url": "classes/Locospec-EnginePhp-Graph.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AaddVertex\u0028\u0029",
            "name": "addVertex",
            "summary": "Adds\u0020a\u0020vertex\u0020to\u0020the\u0020graph",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_addVertex"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AhasEdge\u0028\u0029",
            "name": "hasEdge",
            "summary": "Checks\u0020if\u0020an\u0020edge\u0020already\u0020exists\u0020between\u0020source\u0020and\u0020target\u0020vertices",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_hasEdge"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AaddEdge\u0028\u0029",
            "name": "addEdge",
            "summary": "Adds\u0020an\u0020edge\u0020to\u0020the\u0020graph",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_addEdge"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AgetNeighbors\u0028\u0029",
            "name": "getNeighbors",
            "summary": "Returns\u0020all\u0020edges\u0020connected\u0020to\u0020the\u0020given\u0020vertex",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_getNeighbors"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AhasVertex\u0028\u0029",
            "name": "hasVertex",
            "summary": "Checks\u0020if\u0020a\u0020vertex\u0020exists\u0020in\u0020the\u0020graph",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_hasVertex"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AgetVertex\u0028\u0029",
            "name": "getVertex",
            "summary": "Returns\u0020a\u0020vertex\u0020by\u0020its\u0020ID",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_getVertex"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AgetVertices\u0028\u0029",
            "name": "getVertices",
            "summary": "Returns\u0020all\u0020vertices\u0020in\u0020the\u0020graph",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_getVertices"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AgetAdjacencyList\u0028\u0029",
            "name": "getAdjacencyList",
            "summary": "Returns\u0020the\u0020complete\u0020adjacency\u0020list",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_getAdjacencyList"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AisDirected\u0028\u0029",
            "name": "isDirected",
            "summary": "Returns\u0020whether\u0020the\u0020graph\u0020is\u0020directed",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_isDirected"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AfindShortestPath\u0028\u0029",
            "name": "findShortestPath",
            "summary": "Find\u0020shortest\u0020path\u0020between\u0020two\u0020vertices\u0020using\u0020BFS",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_findShortestPath"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AreconstructEdgePath\u0028\u0029",
            "name": "reconstructEdgePath",
            "summary": "Reconstruct\u0020path\u0020from\u0020parent\u0020edges\u0020map",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_reconstructEdgePath"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AfindAllRelationships\u0028\u0029",
            "name": "findAllRelationships",
            "summary": "Find\u0020all\u0020reachable\u0020entities\u0020and\u0020their\u0020relationship\u0020paths",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_findAllRelationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AdetermineRelationType\u0028\u0029",
            "name": "determineRelationType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_determineRelationType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AgenerateReachableGraph\u0028\u0029",
            "name": "generateReachableGraph",
            "summary": "Generate\u0020a\u0020subgraph\u0020showing\u0020all\u0020reachable\u0020vertices\u0020and\u0020their\u0020relationships",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_generateReachableGraph"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AfindReachableVertices\u0028\u0029",
            "name": "findReachableVertices",
            "summary": "Helper\u0020method\u0020to\u0020find\u0020all\u0020reachable\u0020vertices\u0020using\u0020DFS",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_findReachableVertices"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AcreateExpansionGraph\u0028\u0029",
            "name": "createExpansionGraph",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_createExpansionGraph"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AexpandDFS\u0028\u0029",
            "name": "expandDFS",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_expandDFS"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AtoMermaidSyntax\u0028\u0029",
            "name": "toMermaidSyntax",
            "summary": "Converts\u0020the\u0020graph\u0020to\u0020Mermaid\u0020diagram\u0020syntax",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_toMermaidSyntax"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003AtoMermaidHTML\u0028\u0029",
            "name": "toMermaidHTML",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#method_toMermaidHTML"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003A\u0024vertices",
            "name": "vertices",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#property_vertices"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003A\u0024adjacencyList",
            "name": "adjacencyList",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#property_adjacencyList"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Graph\u003A\u003A\u0024directed",
            "name": "directed",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Graph.html#property_directed"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer",
            "name": "MermaidRenderer",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020MermaidRenderer\u0020instance\u0020with\u0020optional\u0020configuration",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Converts\u0020Mermaid\u0020syntax\u0020to\u0020complete\u0020HTML\u0020page\u0020with\u0020proper\u0020CDN\u0020setup",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html#method_render"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer\u003A\u003AsetCdnUrl\u0028\u0029",
            "name": "setCdnUrl",
            "summary": "Sets\u0020the\u0020Mermaid\u0020CDN\u0020URL",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html#method_setCdnUrl"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer\u003A\u003AsetConfig\u0028\u0029",
            "name": "setConfig",
            "summary": "Updates\u0020Mermaid\u0020configuration",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html#method_setConfig"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer\u003A\u003A\u0024mermaidCdn",
            "name": "mermaidCdn",
            "summary": "The\u0020CDN\u0020URL\u0020for\u0020Mermaid",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html#property_mermaidCdn"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\MermaidRenderer\u003A\u003A\u0024config",
            "name": "config",
            "summary": "Configure\u0020Mermaid\u0020settings",
            "url": "classes/Locospec-EnginePhp-MermaidRenderer.html#property_config"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration",
            "name": "ModelConfiguration",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_fromArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AgetPrimaryKey\u0028\u0029",
            "name": "getPrimaryKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_getPrimaryKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_getTable"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AgetDbOperator\u0028\u0029",
            "name": "getDbOperator",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_getDbOperator"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AgetSingular\u0028\u0029",
            "name": "getSingular",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_getSingular"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AgetPlural\u0028\u0029",
            "name": "getPlural",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_getPlural"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#property_primaryKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#property_table"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003A\u0024dbOperator",
            "name": "dbOperator",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#property_dbOperator"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003A\u0024singular",
            "name": "singular",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#property_singular"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelConfiguration\u003A\u003A\u0024plural",
            "name": "plural",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelConfiguration.html#property_plural"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition",
            "name": "ModelDefinition",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetSingularName\u0028\u0029",
            "name": "getSingularName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getSingularName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetPluralName\u0028\u0029",
            "name": "getPluralName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getPluralName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetConfig\u0028\u0029",
            "name": "getConfig",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getConfig"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AaddRelationship\u0028\u0029",
            "name": "addRelationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_addRelationship"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetRelationship\u0028\u0029",
            "name": "getRelationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getRelationship"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetRelationships\u0028\u0029",
            "name": "getRelationships",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getRelationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AgetRelationshipsByType\u0028\u0029",
            "name": "getRelationshipsByType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_getRelationshipsByType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_fromArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003ArelationshipsToArray\u0028\u0029",
            "name": "relationshipsToArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#method_relationshipsToArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#property_name"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003A\u0024schema",
            "name": "schema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#property_schema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#property_config"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelDefinition\u003A\u003A\u0024relationships",
            "name": "relationships",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelDefinition.html#property_relationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator",
            "name": "ModelValidator",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method_validate"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003AvalidateStructure\u0028\u0029",
            "name": "validateStructure",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method_validateStructure"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003AvalidateName\u0028\u0029",
            "name": "validateName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method_validateName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003AvalidateConfig\u0028\u0029",
            "name": "validateConfig",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method_validateConfig"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003AvalidateRelationships\u0028\u0029",
            "name": "validateRelationships",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method_validateRelationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003AvalidateRelationshipConfig\u0028\u0029",
            "name": "validateRelationshipConfig",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#method_validateRelationshipConfig"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\ModelValidator\u003A\u003A\u0024inflector",
            "name": "inflector",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-ModelValidator.html#property_inflector"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo",
            "name": "BelongsTo",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003AgetOwnerKey\u0028\u0029",
            "name": "getOwnerKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#method_getOwnerKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003AgetForeignKey\u0028\u0029",
            "name": "getForeignKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#method_getForeignKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003AgetQueryPattern\u0028\u0029",
            "name": "getQueryPattern",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#method_getQueryPattern"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003A\u0024foreignKey",
            "name": "foreignKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#property_foreignKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\BelongsTo\u003A\u003A\u0024ownerKey",
            "name": "ownerKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-BelongsTo.html#property_ownerKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany",
            "name": "HasMany",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003AgetLocalKey\u0028\u0029",
            "name": "getLocalKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#method_getLocalKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003AgetForeignKey\u0028\u0029",
            "name": "getForeignKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#method_getForeignKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003AgetQueryPattern\u0028\u0029",
            "name": "getQueryPattern",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#method_getQueryPattern"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003A\u0024foreignKey",
            "name": "foreignKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#property_foreignKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasMany\u003A\u003A\u0024localKey",
            "name": "localKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasMany.html#property_localKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne",
            "name": "HasOne",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AgetLocalKey\u0028\u0029",
            "name": "getLocalKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_getLocalKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AgetForeignKey\u0028\u0029",
            "name": "getForeignKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_getForeignKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AsetSortBy\u0028\u0029",
            "name": "setSortBy",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_setSortBy"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AgetSortBy\u0028\u0029",
            "name": "getSortBy",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_getSortBy"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AgetQueryPattern\u0028\u0029",
            "name": "getQueryPattern",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_getQueryPattern"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003A\u0024foreignKey",
            "name": "foreignKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#property_foreignKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003A\u0024localKey",
            "name": "localKey",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#property_localKey"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\HasOne\u003A\u003A\u0024sortBy",
            "name": "sortBy",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-HasOne.html#property_sortBy"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship",
            "name": "Relationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AgetQueryPattern\u0028\u0029",
            "name": "getQueryPattern",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_getQueryPattern"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AgetRelationshipName\u0028\u0029",
            "name": "getRelationshipName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_getRelationshipName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_getDescription"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_setDescription"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AgetRelatedModelName\u0028\u0029",
            "name": "getRelatedModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_getRelatedModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AsetCurrentModelName\u0028\u0029",
            "name": "setCurrentModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_setCurrentModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AgetCurrentModelName\u0028\u0029",
            "name": "getCurrentModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_getCurrentModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AsetRelatedModelName\u0028\u0029",
            "name": "setRelatedModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_setRelatedModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003A\u0024relationshipName",
            "name": "relationshipName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#property_relationshipName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#property_description"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003A\u0024relatedModelName",
            "name": "relatedModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#property_relatedModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships\\Relationship\u003A\u003A\u0024currentModelName",
            "name": "currentModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Models-Relationships-Relationship.html#property_currentModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ModelParser",
            "name": "ModelParser",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ModelParser.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ModelParser\u003A\u003AparseJson\u0028\u0029",
            "name": "parseJson",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ModelParser.html#method_parseJson"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ModelParser\u003A\u003AparseArray\u0028\u0029",
            "name": "parseArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ModelParser.html#method_parseArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ModelParser\u003A\u003AvalidateModelData\u0028\u0029",
            "name": "validateModelData",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ModelParser.html#method_validateModelData"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserFactory",
            "name": "ParserFactory",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserFactory.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserFactory.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserFactory\u003A\u003AregisterDefaults\u0028\u0029",
            "name": "registerDefaults",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserFactory.html#method_registerDefaults"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserFactory\u003A\u003AregisterParser\u0028\u0029",
            "name": "registerParser",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserFactory.html#method_registerParser"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserFactory\u003A\u003AcreateParser\u0028\u0029",
            "name": "createParser",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserFactory.html#method_createParser"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserFactory\u003A\u003A\u0024parsers",
            "name": "parsers",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserFactory.html#property_parsers"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserInterface",
            "name": "ParserInterface",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserInterface.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserInterface\u003A\u003AparseJson\u0028\u0029",
            "name": "parseJson",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserInterface.html#method_parseJson"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers\\ParserInterface\u003A\u003AparseArray\u0028\u0029",
            "name": "parseArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Parsers-ParserInterface.html#method_parseArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry",
            "name": "AbstractRegistry",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#method_register"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#method_get"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#method_has"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#method_all"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#method_clear"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003AgetItemName\u0028\u0029",
            "name": "getItemName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#method_getItemName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\AbstractRegistry\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-AbstractRegistry.html#property_items"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry",
            "name": "ModelRegistry",
            "summary": "ModelRegistry\u0020manages\u0020the\u0020registration\u0020and\u0020relationship\u0020graphs\u0020of\u0020models.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Get\u0020the\u0020registry\u0020type\u0020identifier.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AgetItemName\u0028\u0029",
            "name": "getItemName",
            "summary": "Get\u0020the\u0020name\u0020identifier\u0020for\u0020a\u0020registry\u0020item.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_getItemName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AgetRelationshipGraph\u0028\u0029",
            "name": "getRelationshipGraph",
            "summary": "Get\u0020the\u0020relationship\u0020graph\u0020for\u0020all\u0020registered\u0020models.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_getRelationshipGraph"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AbuildRelationshipGraph\u0028\u0029",
            "name": "buildRelationshipGraph",
            "summary": "Build\u0020the\u0020relationship\u0020graph\u0020from\u0020registered\u0020models.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_buildRelationshipGraph"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AaddModelsAsVertices\u0028\u0029",
            "name": "addModelsAsVertices",
            "summary": "Add\u0020all\u0020registered\u0020models\u0020as\u0020vertices\u0020in\u0020the\u0020graph.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_addModelsAsVertices"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AaddRelationshipsAsEdges\u0028\u0029",
            "name": "addRelationshipsAsEdges",
            "summary": "Add\u0020all\u0020model\u0020relationships\u0020as\u0020edges\u0020in\u0020the\u0020graph.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_addRelationshipsAsEdges"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AaddRelationshipEdge\u0028\u0029",
            "name": "addRelationshipEdge",
            "summary": "Add\u0020a\u0020single\u0020relationship\u0020as\u0020an\u0020edge\u0020in\u0020the\u0020graph.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_addRelationshipEdge"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AgetRelationshipKeys\u0028\u0029",
            "name": "getRelationshipKeys",
            "summary": "Get\u0020relationship\u0020keys\u0020in\u0020a\u0020consistent\u0020format.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_getRelationshipKeys"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003AgetExpansionGraph\u0028\u0029",
            "name": "getExpansionGraph",
            "summary": "Get\u0020an\u0020expansion\u0020graph\u0020starting\u0020from\u0020a\u0020specific\u0020model.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_getExpansionGraph"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "Clear\u0020the\u0020registry\u0020and\u0020reset\u0020the\u0020graph.",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#method_clear"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\ModelRegistry\u003A\u003A\u0024relationshipGraph",
            "name": "relationshipGraph",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-ModelRegistry.html#property_relationshipGraph"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface",
            "name": "RegistryInterface",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html#method_register"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html#method_get"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html#method_has"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html#method_all"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html#method_clear"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryInterface\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryInterface.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager",
            "name": "RegistryManager",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003AregisterDefaults\u0028\u0029",
            "name": "registerDefaults",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_registerDefaults"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003AaddRegistry\u0028\u0029",
            "name": "addRegistry",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_addRegistry"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003AgetRegistry\u0028\u0029",
            "name": "getRegistry",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_getRegistry"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_register"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_get"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_has"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#method_all"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry\\RegistryManager\u003A\u003A\u0024registries",
            "name": "registries",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Registry-RegistryManager.html#property_registries"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\AbstractSchemaProperty",
            "name": "AbstractSchemaProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-AbstractSchemaProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\AbstractSchemaProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-AbstractSchemaProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\AbstractSchemaProperty\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-AbstractSchemaProperty.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\AbstractSchemaProperty\u003A\u003AsetSchema\u0028\u0029",
            "name": "setSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-AbstractSchemaProperty.html#method_setSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\AbstractSchemaProperty\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-AbstractSchemaProperty.html#method_getSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\AbstractSchemaProperty\u003A\u003A\u0024schema",
            "name": "schema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-AbstractSchemaProperty.html#property_schema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\ArrayProperty",
            "name": "ArrayProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-ArrayProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\ArrayProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-ArrayProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\BooleanProperty",
            "name": "BooleanProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-BooleanProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\BooleanProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-BooleanProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\DateProperty",
            "name": "DateProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-DateProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\DateProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-DateProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\HasSchemaTrait",
            "name": "HasSchemaTrait",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-HasSchemaTrait.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\HasSchemaTrait\u003A\u003AsetSchema\u0028\u0029",
            "name": "setSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-HasSchemaTrait.html#method_setSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\HasSchemaTrait\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-HasSchemaTrait.html#method_getSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\HasSchemaTrait\u003A\u003A\u0024schema",
            "name": "schema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-HasSchemaTrait.html#property_schema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\IntegerProperty",
            "name": "IntegerProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-IntegerProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\IntegerProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-IntegerProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\NullProperty",
            "name": "NullProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-NullProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\NullProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-NullProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\NumberProperty",
            "name": "NumberProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-NumberProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\NumberProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-NumberProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\ObjectProperty",
            "name": "ObjectProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-ObjectProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\ObjectProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-ObjectProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyFactory",
            "name": "SchemaPropertyFactory",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyFactory.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyFactory.html#method_create"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyFactory\u003A\u003AregisterType\u0028\u0029",
            "name": "registerType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyFactory.html#method_registerType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyFactory\u003A\u003A\u0024typeMap",
            "name": "typeMap",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyFactory.html#property_typeMap"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyInterface",
            "name": "SchemaPropertyInterface",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyInterface.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyInterface\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyInterface.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyInterface.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyInterface\u003A\u003AsetSchema\u0028\u0029",
            "name": "setSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyInterface.html#method_setSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\SchemaPropertyInterface\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-SchemaPropertyInterface.html#method_getSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\StringProperty",
            "name": "StringProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-StringProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\StringProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-StringProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\TimestampProperty",
            "name": "TimestampProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-TimestampProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\TimestampProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-TimestampProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\UlidProperty",
            "name": "UlidProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-UlidProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\UlidProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-UlidProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\UuidProperty",
            "name": "UuidProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-UuidProperty.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties\\UuidProperty\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Properties-UuidProperty.html#method_getType"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema",
            "name": "Schema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AaddProperty\u0028\u0029",
            "name": "addProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_addProperty"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AgetProperty\u0028\u0029",
            "name": "getProperty",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_getProperty"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_toArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AtoJson\u0028\u0029",
            "name": "toJson",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_toJson"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_fromArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AtoShortArray\u0028\u0029",
            "name": "toShortArray",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_toShortArray"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003AconvertToShortFormat\u0028\u0029",
            "name": "convertToShortFormat",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#method_convertToShortFormat"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003A\u0024properties",
            "name": "properties",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#property_properties"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#property_title"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Schema\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-Schema.html#property_description"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder",
            "name": "SchemaBuilder",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Astring\u0028\u0029",
            "name": "string",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_string"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Anumber\u0028\u0029",
            "name": "number",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_number"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Ainteger\u0028\u0029",
            "name": "integer",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_integer"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Aboolean\u0028\u0029",
            "name": "boolean",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_boolean"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Aarray\u0028\u0029",
            "name": "array",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_array"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Aobject\u0028\u0029",
            "name": "object",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_object"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Adate\u0028\u0029",
            "name": "date",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_date"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Atimestamp\u0028\u0029",
            "name": "timestamp",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_timestamp"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003Aulid\u0028\u0029",
            "name": "ulid",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_ulid"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#method_getSchema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\SchemaBuilder\u003A\u003A\u0024schema",
            "name": "schema",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Schema-SchemaBuilder.html#property_schema"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor",
            "name": "RelationshipProcessor",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003AprocessModelRelationships\u0028\u0029",
            "name": "processModelRelationships",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method_processModelRelationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003AcreateAndValidateRelationship\u0028\u0029",
            "name": "createAndValidateRelationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method_createAndValidateRelationship"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003AcreateHasOneRelationship\u0028\u0029",
            "name": "createHasOneRelationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method_createHasOneRelationship"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003AcreateBelongsToRelationship\u0028\u0029",
            "name": "createBelongsToRelationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method_createBelongsToRelationship"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003AcreateHasManyRelationship\u0028\u0029",
            "name": "createHasManyRelationship",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method_createHasManyRelationship"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003AdetermineRelatedModelName\u0028\u0029",
            "name": "determineRelatedModelName",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#method_determineRelatedModelName"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003A\u0024registryManager",
            "name": "registryManager",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#property_registryManager"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\RelationshipProcessor\u003A\u003A\u0024inflector",
            "name": "inflector",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-RelationshipProcessor.html#property_inflector"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor",
            "name": "SpecificationProcessor",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003AprocessFile\u0028\u0029",
            "name": "processFile",
            "summary": "Process\u0020specifications\u0020from\u0020a\u0020file\u0020path",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method_processFile"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003AprocessJson\u0028\u0029",
            "name": "processJson",
            "summary": "Process\u0020specifications\u0020from\u0020a\u0020JSON\u0020string",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method_processJson"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003AparseJson\u0028\u0029",
            "name": "parseJson",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method_parseJson"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003AnormalizeSpecifications\u0028\u0029",
            "name": "normalizeSpecifications",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method_normalizeSpecifications"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003AprocessModelDefinition\u0028\u0029",
            "name": "processModelDefinition",
            "summary": "Process\u0020a\u0020single\u0020model\u0020definition\u0020without\u0020relationships",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method_processModelDefinition"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003AprocessAllPendingRelationships\u0028\u0029",
            "name": "processAllPendingRelationships",
            "summary": "Process\u0020all\u0020pending\u0020relationships\u0020after\u0020all\u0020models\u0020are\u0020registered",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#method_processAllPendingRelationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003A\u0024registryManager",
            "name": "registryManager",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#property_registryManager"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003A\u0024parserFactory",
            "name": "parserFactory",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#property_parserFactory"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications\\SpecificationProcessor\u003A\u003A\u0024pendingRelationships",
            "name": "pendingRelationships",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Specifications-SpecificationProcessor.html#property_pendingRelationships"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector",
            "name": "StringInflector",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_getInstance"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003Aplural\u0028\u0029",
            "name": "plural",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_plural"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003Asingular\u0028\u0029",
            "name": "singular",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_singular"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003Acamel\u0028\u0029",
            "name": "camel",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_camel"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003Asnake\u0028\u0029",
            "name": "snake",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_snake"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003Astudly\u0028\u0029",
            "name": "studly",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_studly"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003AclearCache\u0028\u0029",
            "name": "clearCache",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#method_clearCache"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#property_instance"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003A\u0024inflector",
            "name": "inflector",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#property_inflector"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support\\StringInflector\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Support-StringInflector.html#property_cache"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Vertex",
            "name": "Vertex",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Vertex.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Vertex\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020Vertex\u0020instance",
            "url": "classes/Locospec-EnginePhp-Vertex.html#method___construct"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Vertex\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Returns\u0020the\u0020stored\u0020data\u0020payload",
            "url": "classes/Locospec-EnginePhp-Vertex.html#method_getData"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Vertex\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Returns\u0020the\u0020vertex\u0020ID",
            "url": "classes/Locospec-EnginePhp-Vertex.html#method_getId"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Vertex\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Vertex.html#property_id"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Vertex\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Locospec-EnginePhp-Vertex.html#property_data"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp",
            "name": "EnginePhp",
            "summary": "",
            "url": "namespaces/locospec-enginephp.html"
        },                {
            "fqsen": "\\Locospec",
            "name": "Locospec",
            "summary": "",
            "url": "namespaces/locospec.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/locospec-enginephp-exceptions.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/locospec-enginephp-models.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Models\\Relationships",
            "name": "Relationships",
            "summary": "",
            "url": "namespaces/locospec-enginephp-models-relationships.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Parsers",
            "name": "Parsers",
            "summary": "",
            "url": "namespaces/locospec-enginephp-parsers.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Registry",
            "name": "Registry",
            "summary": "",
            "url": "namespaces/locospec-enginephp-registry.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema\\Properties",
            "name": "Properties",
            "summary": "",
            "url": "namespaces/locospec-enginephp-schema-properties.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Schema",
            "name": "Schema",
            "summary": "",
            "url": "namespaces/locospec-enginephp-schema.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Specifications",
            "name": "Specifications",
            "summary": "",
            "url": "namespaces/locospec-enginephp-specifications.html"
        },                {
            "fqsen": "\\Locospec\\EnginePhp\\Support",
            "name": "Support",
            "summary": "",
            "url": "namespaces/locospec-enginephp-support.html"
        }            ]
);
